### ISSUE TITLE
Possible to override less main and path?

### ISSUE THREAD

**Issue by mtraynham** [bootprint/bootprint#15]
Say we only want to `@include` certain portions of bootstrap.  For instance, I don't want to include bootstrap's `print.less`.  How would I go about this?  Everything I've tried still merges the original `bootstrap.less` which has everything.

**Comment by nknapp** [comment]
This ist due to https://github.com/bootprint/customize-engine-less/blob/master/index.js#L28 which converts the entries like  `{  main: 'main.less' }` into the internal representation `{ main: [ 'main.less' ] }`.

At the moment, it is *not* possible to override files.

The thought behind this that you can always override declarations in less-files by appending a new less-file. I have not taken into account that reducing the size of the resulting css-file would be of concern. 

I agree, this should be done. It should be an issue at `customize-engine-less`, but I am not sure how to fix it, and I personally probably won't have the time at the moment. If you want to propose a change, don't hesitate to create a PR. I will then have a look at it.

**Comment by mtraynham** [comment]
I have a pretty crappy workaround, which is to alter the node_modules `bootstrap.less` file before running bootprint.  So I'm not going to attempt a PR.  

My problem does extend beyond reducing the size of the css.  

I use this for static webpage generation, which works great, but when converting the page to PDF (using [node-html-pdf](https://github.com/marcbachmann/node-html-pdf) or [PhantomJS](http://phantomjs.org/screen-capture.html)). it sets the `@media` to `print`.  node-html-pdf uses PhantomJS and ultimately both libraries use QtWebKit, and they run into this [bug](https://github.com/ariya/phantomjs/issues/10374).  Bootstrap [has it's own print styles](https://github.com/twbs/bootstrap/blob/master/less/print.less#L12), that use `!important` flags to wash out the colors of the webpage, which completely jacks the color scheme.  I was hoping I could replace the `bootstrap.less` file with my own that removes the `@import "print.less"` through the configuration.

Customize.js has that `_customize_custom_overrider`, which looked promising, but I could never get it to work.

**Comment by nknapp** [comment]
I have changed the title to reflect your actual goal on this, so that other people can find it as well.

At the moment, I don't see a good alternative for the hacky workaround. Which is sad, because the whole idea of `customize` was to allow easy customizations, so this *should* be possible somehow.
I will have to think about it.

**Comment by nknapp** [comment]
You might be able to override the css style similar to the example in http://stackoverflow.com/questions/9636132/list-style-css-override-back-to-default (using `inherit` along with `!important`). Since your styles are included after the bootstrap-styles, they should override them if they are equal specific.
