### ISSUE TITLE
Potential Security Risk

### ISSUE THREAD

**Issue by dorothythurston** [bootprint/bootprint#44]
Hi I just wanted to note this as this project is using event-stream
https://github.com/dominictarr/event-stream/issues/116

**Comment by nknapp** [comment]
Thank you. I will have a look this evening.

**Comment by nknapp** [comment]
Sorry, I could not do it yesterday... I would appreciate any help in this matter.

Could anybody look where event-streams is actually uses in the dependency tree? And where it is actually called?

Is it an affected version?

And if this is a security risk, could anyone file a report for the node security database?

**Comment by nknapp** [comment]
I have researched a bit, but I think this problem is resolved: `event-stream` is now owned by npm itself. There are no dependencies to the mentioned malicious packages anymore, not even in the latest version, so I think we can safely keep the dependencies.

Just a note to myself: Never give away package ownership of popular packages easily, unless you know the people. I have done this myself, but I have been lucky so far.
